name: release

on:
  release:
    types: [ "created" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: release
    
    steps:
      - uses: actions/checkout@v3
      #set up java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      
      - name: maven-settings-temporary
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: '[{ "id": "ossrh", "username": "${{ secrets.OSSRH_USERNAME }}", "password": "${{ secrets.OSSRH_TOKEN }}" }]'

      - id: publish-to-central
        name: Publish to Central Repository
        run: mvn --no-transfer-progress --batch-mode -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} clean deploy
