name: release

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Test
        run: |
          mvn -B test --file pom.xml

      - name: Create Package
        run: |
          mvn clean package

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
          package-name: release-please-action
          extra-files: |
            ./target/${{ github.event.repository.name }}-${{ env.master_version }}.jar
            ./target/${{ github.event.repository.name }}-${{ env.master_version }}-javadoc.jar
            ./target/${{ github.event.repository.name }}-${{ env.master_version }}-sources.jar
        
            
