name: Run Test

on:
  push:
    branches-ignore: "master"

jobs:
  test:
    name: Run Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #set up java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Test
        run: mvn -B test --file pom.xml
